name:                HaskellBot
version:             0.1.0.0
github:              "githubuser/HaskellBot"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/HaskellBot#readme>

dependencies:
- base
- telegram-bot-simple
- text
- time
- mtl
- persistent
- persistent-postgresql
- persistent-template
- esqueleto
- monad-logger
- monad-control
- transformers


library:
  source-dirs: src

executables:
  HaskellBot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellBot

tests:
  HaskellBot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellBot
